### ISSUE TITLE
Uncaught TypeError when using SendNscaFactory::ENCRYPT_NONE encryptor

### ISSUE THREAD

**Issue by geoffroya** [Mizzrym/php_send_nsca#15]
Hi

With PHP >= 7.1, seems that null is rejected as return value, when return type is declared.
This causes an issue with ENCRYPT_NONE, as SendNscaFactory::getEncryptor expects EncryptorInterface, but null is returned when cipher is ENCRYPT_NONE.

I propose to chang the declaration to allow null value.

**Comment by geoffroya** [comment]
Here's the PR https://github.com/Mizzrym/php_send_nsca/pull/16

**Comment by geoffroya** [comment]
Hi @Mizzrym 
Than you for merging. Do you know when the composer repo will be updated and provide v3.0.2?
Best regards

**Comment by Mizzrym** [comment]
I just updated it there. 
Thanks :)

**Comment by Mizzrym** [comment]
Since the nullable type has been added in PHP 7.1 i removed it again to restore compatibility with 7.0 again. Instead i implemented a "NullEncryptor", so that the Interface will always get returned. 
If you run into any issues with this, please let me know. 
Have a nice day :)
