### ISSUE TITLE
Prepare for PHP 7.2

### ISSUE THREAD

**Issue by Mizzrym** [Mizzrym/php_send_nsca#6]
mcrypt support will be dropped, which means everything has to be re-implemented using openssl or another crypto library.

**Comment by nueaf** [comment]
I made a branch for openssl with some basic support. Could only get it to work with DES using DES-CFB8 openssl cipher. No luck with the other ciphers.

**Comment by Mizzrym** [comment]
Made it work with Triple-DES as well, but it seems like the other ciphers aren't really supported. 
Fixed in 2.0.0. 
Thanks for the help :)
