### ISSUE TITLE
Remove duplicate packagist entry

### ISSUE THREAD

**Issue by Mizzrym** [Mizzrym/php_send_nsca#7]
@nueaf i made you contributor to this project both here and on packagist and merged everything together. Would be nice if you could remove your packagist entry for this project and use mine instead. Thanks.

**Comment by nueaf** [comment]
I cannot remove the other package on packagist as there are at least one project out there which depend on it. But i've marked it as abandoned at referenced the original package.

**Comment by Mizzrym** [comment]
Thanks :)
